## This set of configs WILL BE read from yours site's _config.yml if available,
# otherwise the default values will be used

#  Header menu items
menu:
  Home: /
  Blog: /blog

rss: /atom.xml

excerpt_link: Read More


# widget behavior
archive_type: 'monthly'
show_count: false


# ### The next set of settings are Theme related an will NOT be read from your site's _config
# you still can change the values here if you wish.
